val lise2019sub = sc.textFile("/user/cloudera/source/siynvlise.csv")
val lise2019sublow  = lise2019sub.map(x => x.toLowerCase())
val lise2019subrep = lise2019sublow.map(x => x.replace('ş', 's').replace('ı', 'i').replace('ğ', 'g').replace('ü', 'u').replace('ç', 'c').replace('ö', 'o'))
val lise2019subsplit  = lise2019subrep.flatMap(x => x.split("\\W+"))
val lise2019count = lise2019subsplit.map(x => (x, 1)).reduceByKey( (x,y) => x + y )
val stopwords = sc.textFile("/user/cloudera/stopwords")
val stopwordslow  = stopwords.map(x => x.toLowerCase())
val stopwordslowrep = stopwordslow.map(x => x.replace('ş', 's').replace('ı', 'i').replace('ğ', 'g').replace('ü', 'u').replace('ç', 'c').replace('ö', 'o'))
val stopwordskey = stopwordslowrep.map(x => (x, 1)).reduceByKey( (x,y) => x + y )
val lise2019stop = lise2019count.subtractByKey(stopwordskey)
val wordCountsSorted = lise2019stop.map( x => (x._2, x._1) ).sortByKey(false)
val wordCountsSorteddf = spark.createDataFrame(wordCountsSorted)
val wordCountsSorteddfrename = wordCountsSorteddf.withColumnRenamed("_1","kelime_sayisi").withColumnRenamed("_2","kelime")
val koksozluk = spark.read.option("header", "true").option("delimiter", "|").csv("/user/cloudera/koksozluk.csv")
wordCountsSorteddfrename.createOrReplaceTempView("wordCountsSorteddfrename")
koksozluk.createOrReplaceTempView("koksozluk")
val joindf = spark.sql("SELECT sum(wordCountsSorteddfrename.kelime_sayisi) as kelime_sayisi,koksozluk.kok as kelime  FROM koksozluk JOIN wordCountsSorteddfrename ON koksozluk.kelime = wordCountsSorteddfrename.kelime where LENGTH(koksozluk.kok) >3  group by koksozluk.kok order by sum(wordCountsSorteddfrename.kelime_sayisi) desc")
val stopwordskeydf = spark.createDataFrame(stopwordskey)
val stopwordskeydfrename = stopwordskeydf.withColumnRenamed("_1","key").withColumnRenamed("_2","kelime")
stopwordskeydfrename.createOrReplaceTempView("stopwordskeydfrename")
joindf.createOrReplaceTempView("joindf")
val joindfstop = spark.sql("SELECT joindf.kelime_sayisi, joindf.kelime FROM joindf LEFT OUTER JOIN stopwordskeydfrename ON (joindf.kelime = stopwordskeydfrename.kelime) WHERE stopwordskeydfrename.kelime IS null")
joindfstop.coalesce(1).write.csv("/user/cloudera/target/siynvlise.csv")
